---
- name: removing /dev/sdc partitions
  hosts: all
  tasks:
    - name: Remove partition number 1
      community.general.parted:
        device: /dev/sdc
        number: 1
        state: absent
      when: " 'sdc' in ansible_facts['devices'] "
...
